@startuml diagrama-clases
hide circle
skinparam classAttributeIconSize 0
skinparam backgroundColor transparent
skinparam monochrome true
skinparam shadowing false
skinparam roundcorner 0

Class LED {
  - port : Integer
  - gpio : Integer
  - logica : Integer
  - esta_prendido : Boolean
  + <<create>> LED(port : Integer, gpio : Integer, logica : Integer, es_opendrain : Boolean)
  + apagar()
  + prender()
  + alternar()
}

Interface Actualizable <<interface>> {
  + actualizar()
}

Class Boton {
  - port : Integer
  - gpio : Integer
  - estado : Integer
  - estado_anterior : Integer
  - logica : logic_t
  - ventana : Integer
  - flanco_ascendente : Boolean
  - flanco_descendente : Boolean
  + <<create>> Boton(port : Integer, gpio : Integer, logica : logic_t, es_pull_up_down : Boolean)
  + estaActivo() : Boolean
  + huboFlancoAscendente() : Boolean
  + huboFlancoDescendente() : Boolean
  + actualizar()
}

Class ManejadorTareasPeriodicas {
  ticks : Integer[]
  delta_ticks : Integer[]
  cont_tareas : Integer
  - ManejadorTareasPeriodicas()
  + <<create>> <u> obtenerInstancia()</u>
  + registrarTarea(tarea : Actualizable, tick : Integer) : Boolean
  + tick()
}

Actualizable <|-- Boton
ManejadorTareasPeriodicas "1" -> "*" Actualizable : tareas
@enduml